lib: Add an optional `advertised_addresses` for `NetworkSettings`
nimiq/core-rs-albatross pull request #1507
Opened 2023-03-25 17:47 UTC by jsdanielh

Add an optional `advertised_addresses` for `NetworkSettings` in the configuration file  such that the client can use them as the addresses in the `PeerContact` which end up being advertised to other peers.

## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [X] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2023-03-25 17:56 UTC, viquezclaudio requested changes

2023-03-25 17:56 UTC, viquezclaudio commented on lib/src/config/config_file/client.example.toml
> +# Optionally use advertised addresses to advertised other peers addresses different
Optionally use advertised addresses to *advertise* other peers ...

2023-03-26 16:34 UTC, sisou commented on lib/src/config/config_file/client.example.toml
> +# from the ones in `listen_addresses`
```suggestion
# Optionally specify different address(es) from the ones in `listen_addresses` instead
# that will be advertised to peers
```

2023-03-27 00:30 UTC, sisou commented on lib/src/config/config_file/client.example.toml
> +#        "/ip4/0.0.0.0/tcp/9100/ws",
```suggestion
#        "/dns4/my.public.domain.com/tcp/8443/wss",
```

2023-03-27 14:54 UTC, viquezclaudio approved these changes

2023-03-27 14:55 UTC, merged