Handle properly closing the WS connection
nimiq/core-rs-albatross pull request #1620
Opened 2023-05-22 19:22 UTC by viquezclaudio

Closes #1057

## What's in this pull request?

...
#### This fixes #1057 .

## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2023-05-22 19:23 UTC, viquezclaudio commented
Requires:
https://github.com/nimiq/jsonrpc/pull/12

2023-05-22 20:00 UTC, jsdanielh requested changes
Need to update `nimiq-json-rpc` dependencies

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/main.rs
> +    pub async fn close(&mut self) {
Add some `rustdoc` documentation

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/accounts_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/blockchain_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/mempool_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/network_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/policy_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/transactions_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/validator_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 20:00 UTC, jsdanielh commented on rpc-client/src/subcommands/zkp_component_subcommands.rs
> +use tokio::sync::RwLock;
We should be using `parking_lot`

2023-05-22 22:03 UTC, jsdanielh requested changes

2023-05-22 22:03 UTC, jsdanielh commented on rpc-client/src/main.rs
> +
Remove extra line

2023-05-22 22:03 UTC, jsdanielh commented on rpc-client/src/main.rs
> +        let _ = self.ws_client.close().await;
Remove clippy warning:
```suggestion
        self.ws_client.close().await;
```

2023-05-23 00:06 UTC, jsdanielh approved these changes

2023-05-23 11:53 UTC, merged