Iipb/mdbx update
nimiq/core-rs-albatross pull request #1631
Opened 2023-06-05 15:15 UTC by ii-cruz

## What's in this pull request?
Updating libmdbx version. Replaced the use of cursors to the iterators now supported by mdbx. 

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

2023-06-06 06:35 UTC, sisou commented
Also closes #1591.

2023-06-06 06:36 UTC, sisou commented
Why the change to iterators? Are they more performant? Do they have other properties that we like?

2023-06-06 07:34 UTC, ii-cruz commented
Iterators are easier to read and understand. The code also looks simpler. In terms of efficiency, we believe it to be rather similar.

2023-06-06 17:29 UTC, jsdanielh commented on block-production/tests/mod.rs
> +use nimiq_database::traits::WriteTransaction;
I'd move it below with all `nimiq_database` entries

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/blockchain/blockchain.rs
> +use nimiq_database::traits::{Database, WriteTransaction};
I'd move this to the `nimiq_database` entries below

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/blockchain/zkp_sync.rs
> +use nimiq_database::traits::{ReadTransaction, WriteTransaction};
I'd move this include where all `nimiq` includes are

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/mmr_store.rs
> +use nimiq_database::{TableProxy, TransactionProxy, WriteTransactionProxy};
```suggestion
use nimiq_database::{traits::{ReadCursor, ReadTransaction, WriteTransaction}, TableProxy, TransactionProxy, WriteTransactionProxy};
```

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/tests/inherents.rs
> +use nimiq_database::volatile::VolatileDatabase;
```suggestion
use nimiq_database::{traits::WriteTransaction, volatile::VolatileDatabase};
```

2023-06-06 17:29 UTC, jsdanielh commented on consensus/src/sync/light/sync_stream.rs
> +    use nimiq_database::traits::WriteTransaction;
I'd move the include in the `nimiq-database` listing below.

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/cursor.rs
> +use nimiq_database_value::{AsDatabaseBytes, FromDatabaseValue};
```suggestion
use libmdbx::{TransactionKind, WriteFlags, RO, RW};

use nimiq_database_value::{AsDatabaseBytes, FromDatabaseValue};
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/cursor.rs
> +use super::DbKvPair;
I'd merge this include into the `super` listing above

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/cursor.rs
> +pub struct MdbxCursor<'txn, K: TransactionKind> {
Could you add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/cursor.rs
> +pub type MdbxReadCursor<'txn> = MdbxCursor<'txn, RO>;
Could you add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/cursor.rs
> +pub type MdbxWriteCursor<'txn> = MdbxCursor<'txn, RW>;
Could you add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on validator/src/validator.rs
> +use nimiq_database::traits::Database;
I'd move the include to the `nimiq-database` listing below

2023-06-06 17:29 UTC, jsdanielh commented on rpc-server/src/dispatchers/wallet.rs
> +use nimiq_database::traits::WriteTransaction;
I'd move the include to the `nimiq` includes below

2023-06-06 17:29 UTC, jsdanielh commented on primitives/account/tests/staking_contract.rs
> +use nimiq_database::volatile::VolatileDatabase;
```suggestion
use nimiq_database::{traits::Database, volatile::VolatileDatabase};
```

2023-06-06 17:29 UTC, jsdanielh commented on primitives/account/src/data_store.rs
> +    use nimiq_database::volatile::VolatileDatabase;
```suggestion
    use nimiq_database::{traits::{Database, WriteTransaction}, volatile::VolatileDatabase};
```

2023-06-06 17:29 UTC, jsdanielh commented on genesis-builder/src/lib.rs
> +use nimiq_database::traits::{Database, WriteTransaction};
I'd move this include to the `nimiq-database` listing below

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/chain_store.rs
> +                    .expect("Corrupted store: Block referenced from index not found"),
Maybe include the block hash as well?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
> +use nimiq_database::traits::{Database, ReadTransaction, WriteTransaction};
Maybe collapse both `nimiq-database` includes?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
>      // A database of all history trees indexed by their epoch number.
A table maybe? And also, could you convert it to `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
>      // A database of all extended transactions indexed by their hash (= leaf hash in the history
A table maybe? And also, could you convert it to `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
>      // A database of all leaf hashes and indexes indexed by the hash of the transaction. This way we
A table maybe? And also, could you convert it to `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
>      // A database of the last leaf index for each block number.
A table maybe? And also, could you convert it to `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on blockchain/src/history/history_store.rs
>      // A database of all transaction (and reward inherent) hashes indexed by their sender and
A table maybe? And also, could you convert it to `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/lib.rs
>  pub mod volatile;
Could you add some `rustdoc` for the public modules?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +        // This is an implicit transaction, so take the lock first.
```suggestion
        // This is an implicit transaction, so take the lock first
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +        // Translate flags.
```suggestion
        // Translate flags
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +pub struct MdbxDatabase {
Could you add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +        // This is only required if multiple databases will be used in the environment.
```suggestion
        // This is only required if multiple databases will be used in the environment
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +        // This is only required if multiple databases will be used in the environment.
And we no longer have the concept of environment/databases, do we? Maybe tables in databases now?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +        info!("MDBX memory map size: {}", cur_mapsize);
Use tracing style:
```suggestion
        info!(cur_mapsize, "MDBX memory map size");
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +            info!("MDBX memory needs to be resized.");
```suggestion
            info!("MDBX memory needs to be resized");
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +            info!("Size threshold: {}", threshold_size);
```suggestion
            info!( threshold-based, map_size=info.map_size(), size_used, space_remaining=info.map_size() - size_used, threshold_size, "DB settings:");
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +            );
```suggestion
            info!(map_size=info.map_size(), size_used, space_remaining = info.map_size() - size_used, percent_used=                (size_used as f64) / (info.map_size() as f64), "DB resize (percent-based)");
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/database.rs
> +pub struct MdbxTable {
Could you add `rustdoc` to it?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/iterators.rs
> +pub struct IntoIter<'txn, Kind: TransactionKind, K: FromDatabaseValue, V: FromDatabaseValue> {
Could you add `rustdoc` to it?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/mod.rs
> +            // Have a new ReadTransaction read the smallest value.
```suggestion
            // Have a new ReadTransaction read the smaller value.
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/mod.rs
> +            //            assert_eq!(cursor.seek_range_key::<String, u32>("test"), Some((test1.clone(), 12)));
Maybe remove it?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/transaction.rs
> +use nimiq_database_value::{AsDatabaseBytes, FromDatabaseValue, IntoDatabaseValue};
```suggestion
use libmdbx::{NoWriteMap, TransactionKind, WriteFlags, RO, RW};

use nimiq_database_value::{AsDatabaseBytes, FromDatabaseValue, IntoDatabaseValue};
```

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/transaction.rs
> +pub struct MdbxTransaction<'db, K: TransactionKind> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/transaction.rs
> +pub type MdbxReadTransaction<'db> = MdbxTransaction<'db, RO>;
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/mdbx/transaction.rs
> +pub type MdbxWriteTransaction<'db> = MdbxTransaction<'db, RW>;
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/cursor.rs
> +pub enum CursorProxy<'txn> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/cursor.rs
> +pub enum IntoIterProxy<'txn, K: FromDatabaseValue, V: FromDatabaseValue> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/database.rs
> +pub enum DatabaseProxy {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/mod.rs
> +pub type TableProxy = MdbxTable;
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/mod.rs
> +pub type Cursor<'txn> = <TransactionProxy<'txn> as ReadTransaction<'txn>>::Cursor<'txn>;
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/mod.rs
> +pub type WriteCursor<'txn> =
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/transaction.rs
> +pub enum TransactionProxy<'db> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/proxy/transaction.rs
> +pub struct WriteTransactionProxy<'db> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/traits/cursor.rs
> +pub trait ReadCursor<'txn>: Clone {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/traits/cursor.rs
> +pub trait WriteCursor<'txn>: ReadCursor<'txn> {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/traits/database.rs
> +pub trait Database: Sized {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/traits/transaction.rs
> +pub trait ReadTransaction<'db>: Sized {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/traits/transaction.rs
> +pub trait WriteTransaction<'db>: ReadTransaction<'db> + Sized {
Maybe add some `rustdoc`?

2023-06-06 17:29 UTC, jsdanielh commented on database/src/volatile.rs
> +pub struct VolatileDatabase {
Maybe add some `rustdoc`?

2023-06-07 09:57 UTC, jsdanielh requested changes

2023-06-07 09:57 UTC, jsdanielh commented on blockchain/src/history/mmr_store.rs
> +            hist_tree_table: hist_tree_table,
Could you fix this clippy error?

2023-06-07 09:57 UTC, jsdanielh commented on blockchain/src/chain_store.rs
> +                    )),
Could you fix this clippy warning?

2023-06-07 11:22 UTC, jsdanielh approved these changes

2023-06-07 15:58 UTC, merged