Expose BLS functionality trough web-client
nimiq/core-rs-albatross pull request #1673
Opened 2023-06-29 20:28 UTC by viquezclaudio

This is required by the POS migration tool in order to generate and import BLS keys.
This functionality needs to be compiled and exposed for NodeJS

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2023-06-29 20:39 UTC, jsdanielh requested changes

2023-06-29 20:39 UTC, jsdanielh commented on web-client/Cargo.toml
> +nimiq-bls = {path = "../bls"}
```suggestion
nimiq-bls = { path = "../bls" }
```

2023-06-29 20:39 UTC, jsdanielh commented on web-client/dist/package-lock.json
> +{
Added file by mistake?

2023-06-30 14:25 UTC, jsdanielh requested changes

2023-06-30 14:25 UTC, jsdanielh commented on web-client/src/client/mod.rs
> +pub mod client;
Could you address this clippy warning?

2023-06-30 14:27 UTC, jsdanielh commented
There are several clippy warnings, could you address them?

2023-06-30 15:33 UTC, jsdanielh approved these changes

2023-07-03 09:11 UTC, sisou approved these changes

2023-07-04 00:05 UTC, jsdanielh requested changes

2023-07-04 00:05 UTC, jsdanielh commented on web-client/src/primitives/bls_secret_key.rs
> +        let key = nimiq_bls::SecretKey::deserialize_from_vec(&mut &*bytes)?;
Clippy warning, could you fix it?

2023-07-04 00:05 UTC, jsdanielh commented on web-client/src/primitives/bls_public_key.rs
> +        let key = nimiq_bls::PublicKey::deserialize_from_vec(&mut &*bytes)?;
Clippy warning, could you fix it?

2023-07-04 00:05 UTC, jsdanielh commented on web-client/src/primitives/bls_key_pair.rs
> +        let key_pair = nimiq_bls::KeyPair::deserialize_from_vec(&mut &*bytes)?;
Clippy warning, could you fix it?

2023-07-04 16:16 UTC, jsdanielh requested changes
There are still a couple of clippy warnings

2023-07-04 16:56 UTC, jsdanielh requested changes

2023-07-04 16:56 UTC, jsdanielh commented on web-client/src/primitives/bls_key_pair.rs
> +        vec.push(0);
Why are we pushing an extra `0u8`?

2023-07-04 16:56 UTC, jsdanielh commented on web-client/src/primitives/bls_secret_key.rs
> +        // 95 and 96 byres are valid sizes.
```suggestion
        // 95 and 96 bytes are valid sizes.
```

2023-07-04 16:56 UTC, jsdanielh commented on web-client/src/primitives/bls_secret_key.rs
> +        // 95 and 96 byres are valid sizes.
96 bytes are no longer valid

2023-07-04 17:49 UTC, jsdanielh requested changes

2023-07-04 17:49 UTC, jsdanielh commented on web-client/src/primitives/bls_key_pair.rs
> +        vec
This would remove the clippy warning:
```suggestion
        self.inner.serialize_to_vec()
```

2023-07-04 21:55 UTC, jsdanielh approved these changes

2023-07-05 14:43 UTC, jsdanielh approved these changes

2023-07-05 15:35 UTC, merged