Update system requirements
nimiq/core-rs-albatross pull request #2025
Opened 2023-11-30 19:12 UTC by viquezclaudio

2023-11-30 21:16 UTC, sisou commented on README.md
> +- 5GB of disk space (100GB of more is required for history nodes)
```suggestion
- 5GB of disk space (100GB or more is required for history nodes)
```

2023-12-01 10:09 UTC, Eligioo requested changes, later dismissed

2023-12-01 10:09 UTC, Eligioo commented on README.md
> +- 5GB of free disk space (100GB or more is required for history nodes)
```suggestion
- 5GB of free disk space, an SSD is highly recommended (100GB or more is required for history nodes)
```

2023-12-04 14:41 UTC, jsdanielh reviewed
I was thinking more on adding a section of _recommended system specs_ and that we could differentiate between full vs history nodes there

2023-12-05 22:02 UTC, jsdanielh approved these changes

2023-12-05 22:30 UTC, merged