Add missing fields to RPC Policy dispatcher
nimiq/core-rs-albatross pull request #2210
Opened 2024-02-12 11:08 UTC by sisou

Recently added fields, such as minimum_stake, jail_epochs and related methods were missing. I also added the genesis_block_number and removed two 0-checks that became unnessary.

- [ ] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2024-02-12 13:17 UTC, Eligioo commented on rpc-server/src/dispatchers/policy.rs
>              return Err(Error::BlockNumberNotZero);
I would update the predicate here to check that the `block_number` if before the genesis block. This could easily be checked with `block_number < Policy::genesis_block_number()`. This would prevent the panic as this could be a potential DoS on public RPC nodes.

2024-02-12 13:17 UTC, Eligioo commented on rpc-server/src/dispatchers/policy.rs
> +        // Policy::last_election_block panics when queried block number is before genesis block!
Same as previous comment.

2024-02-12 13:17 UTC, Eligioo commented on rpc-server/src/dispatchers/policy.rs
> +        // Policy::macro_block_before panics when queried block number is before genesis block!
Same comment

2024-02-12 13:56 UTC, sisou commented on rpc-server/src/dispatchers/policy.rs
>              return Err(Error::BlockNumberNotZero);
Thanks, I did that now :+1:

2024-02-12 14:12 UTC, Eligioo approved these changes

2024-02-14 00:58 UTC, jsdanielh requested changes

2024-02-14 00:58 UTC, jsdanielh commented on rpc-server/src/dispatchers/policy.rs
> +    async fn get_block_after_reporting_window(
Could you add some rustdoc?

2024-02-14 00:58 UTC, jsdanielh commented on rpc-server/src/dispatchers/policy.rs
> +    async fn get_block_after_jail(&mut self, block_number: u32) -> RPCResult<u32, (), Self::Error> {
Could you add some rustdoc?

2024-02-14 00:58 UTC, jsdanielh commented on rpc-server/src/error.rs
> +    BlockNumberBeforeGenenis,
```suggestion
    BlockNumberBeforeGenesis,
```

2024-02-14 00:58 UTC, jsdanielh commented on rpc-server/src/dispatchers/policy.rs
> +            return Err(Error::BlockNumberBeforeGenenis);
```suggestion
            return Err(Error::BlockNumberBeforeGenesis);
```

2024-02-15 13:44 UTC, sisou commented on rpc-server/src/dispatchers/policy.rs
> +    async fn get_block_after_reporting_window(
Certainly, my Lord 🫡

2024-02-15 15:07 UTC, jsdanielh approved these changes

2024-02-15 15:43 UTC, merged