Draft: Store decompressed BlsPublicKeys in IndexedDB
nimiq/core-rs-albatross pull request #3174
Opened 2024-12-02 19:40 UTC by fiaxh

## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2024-12-02 19:44 UTC, sisou commented
Without understanding/thoroughly reading the code: is this Indexeddb cache optional? Will it fail without crashing the client?

Indexeddb might not be available in all browser contexts nor in NodeJS, so this needs to be purely optional and not affect the client if not available or unwritable/unreadable for any other reason.

2024-12-11 12:26 UTC, hrxi commented
> Without understanding/thoroughly reading the code: is this Indexeddb cache optional? Will it fail without crashing the client?

Yes, it's in an `Option` and just does nothing when it's not available.

2024-12-16 14:29 UTC, hrxi reviewed
There's still [an error in the web client compilation](https://github.com/nimiq/core-rs-albatross/actions/runs/12126731599/job/33809448345):
```
Generating main WASM for target nodejs...
error: 

it looks like the Rust project used to create this Wasm file was linked against
version of wasm-bindgen that uses a different bindgen format than this binary:

  rust Wasm file schema version: 0.2.95
     this binary schema version: 0.2.97

Currently the bindgen format is unstable enough that these two schema versions
must exactly match. You can accomplish this by either updating this binary or
the wasm-bindgen dependency in the Rust project.

You should be able to update the wasm-bindgen dependency with:

    cargo update -p wasm-bindgen --precise 0.2.97

don't forget to recompile your Wasm file! Alternatively, you can update the
binary with:

    cargo install -f wasm-bindgen-cli --version 0.2.95

if this warning fails to go away though and you're not sure what to do feel free
to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
```

2024-12-16 14:29 UTC, hrxi commented on web-client/Cargo.toml
> +idb = "0.6.4"
Alphabetical.

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                    .unwrap()
Is it the function's contract that you may only pass valid keys? If so, we should specify that in the documentation. If not, we should not `unwrap` here, but skip the iteration instead.

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                key.uncompress()
This is a potentially expensive operation. We should probably tell the caller that the keys should have been uncompressed before already.

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                let compressed_key = hex::encode(key.compressed().serialize_to_vec());
Can the data also be stored without the hex encoding, i.e. directly as bytes in the IndexedDB?

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/lib.rs
> +                let (hash, reason, reverted_blocks, adopted_blocks_hashs) =
```suggestion
                let (hash, reason, reverted_blocks, adopted_block_hashes) =
```

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/lib.rs
> +                args.push(&adopted_blocks.clone());
```suggestion
                args.push(&adopted_blocks);
```

2024-12-16 14:29 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +    public_key: String,
We talked about adding a "last used" field so we can apply some sort of cache eviction in the future.

2024-12-17 11:05 UTC, sisou commented
The wasm-bindgen version missmatch will go away when rebasing on top of `albatross`, as those packages where updated recently to match.

2024-12-18 10:28 UTC, hrxi commented
Rebased on top of albatross.

2025-01-23 16:55 UTC, hrxi commented on web-client/Cargo.toml
> +idb = "0.6.4"
Done.

2025-01-23 16:55 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                    .unwrap()
Specified.

2025-01-23 16:55 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                key.uncompress()
Told the caller.

2025-01-23 16:55 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                let compressed_key = hex::encode(key.compressed().serialize_to_vec());
Yes. Done.

2025-01-24 19:43 UTC, nibhar requested changes
Generally looks good to me. Left some minor comments only. It however does still have 2 clippy warnings for a `RefCell` which is held across an `.await`. Those should be reseolved.

I would also like to see some more rustdoc added, where it is missing.

2025-01-24 19:43 UTC, nibhar commented on bls/src/types/public_key.rs
> +    pub const TRUSTED_SERIALIZATION_SIZE: usize = 570;
Is this the same as `PUBLIC_KEY_SIZE`? If so I would prefer to name this `SIZE`, similar to `CompressedPublicKey::SIZE`.

```suggestion
    /// The size of a serialized PublicKey in bytes.
    pub const SIZE: usize = 570;
```

2025-01-24 19:43 UTC, nibhar commented on bls/src/types/public_key.rs
> +        affine.serialize_compressed(&mut buffer[..]).unwrap();
More an out of interest question:
When does this return `Err(_)`? I realize the `.unwrap()` was there before, but obviously you took care of non fitting buffers. Is this now no longer failing for any reason?

2025-01-24 19:43 UTC, nibhar commented on bls/src/types/public_key.rs
> +    pub fn trusted_serialize(&self) -> [u8; PublicKey::TRUSTED_SERIALIZATION_SIZE] {
I would prefer to see a rustdoc, explaining what makes this trusted and how it can fail.

2025-01-24 19:43 UTC, nibhar commented on bls/src/types/public_key.rs
> +    pub fn trusted_deserialize(
I would prefer to see a rustdoc, explaining what makes this trusted and how it can fail.

2025-01-24 19:43 UTC, nibhar commented on genesis-builder/src/lib.rs
> +        }
You may be able to use `block.validators().expect()` here as that will give you the `Validators` as well and is a bit shorter and potentially better readable.

2025-01-27 11:19 UTC, hrxi commented on bls/src/types/public_key.rs
> +        affine.serialize_compressed(&mut buffer[..]).unwrap();
The error type is [`ark_serialize::SerializationError`](https://docs.rs/ark-serialize/0.5.0/ark_serialize/enum.SerializationError.html):
- `NotEnoughSpace` — not applicable, we give a correctly sized buffer (also verified by the assert).
- `InvalidData` — not sure how the incoming data can be incorrect, but we'd like to know about it.
- `UnexpectedFlags` — programming error, should panic.
- `IoError` — can't happen, we don't serialize with IO, should be unreachable.

2025-01-27 11:24 UTC, hrxi commented on bls/src/types/public_key.rs
> +    pub const TRUSTED_SERIALIZATION_SIZE: usize = 570;
Added some docs. No, it's specific to the trusted serialization, and should generally not be used, unless you know that you can trust the place where you got the serialization from. The normal public key serialization has 285 bytes.

2025-01-27 11:24 UTC, hrxi commented on bls/src/types/public_key.rs
> +    pub fn trusted_serialize(&self) -> [u8; PublicKey::TRUSTED_SERIALIZATION_SIZE] {
Done. Cannot fail.

2025-01-27 11:24 UTC, hrxi commented on bls/src/types/public_key.rs
> +    pub fn trusted_deserialize(
Done. Cannot fail (unless you give it untrusted data).

2025-01-27 11:24 UTC, hrxi commented on genesis-builder/src/lib.rs
> +        }
Done.

2025-01-27 15:21 UTC, hrxi commented
> Generally looks good to me. Left some minor comments only. It however does still have 2 clippy warnings for a `RefCell` which is held across an `.await`. Those should be reseolved.

Done.

2025-01-30 12:40 UTC, Eligioo commented on bls/src/types/compressed_public_key.rs
> +        log::info!("decompressing {}", &self.to_hex()[..16]);
Tracing style logging, should it be `INFO`?

2025-01-30 12:40 UTC, Eligioo commented on web-client/src/client/bls_cache.rs
> +                log::warn!("idb: Couldn't create database {}", err);
Tracing style log

2025-01-30 12:40 UTC, Eligioo commented on web-client/src/client/lib.rs
> +                    }
```suggestion
                  let Ok(Block::Macro(macro_block)) = blockchain.read().get_block(hash, false)
                    else {
                        continue;
                    };

                    let Some(validators) = macro_block.header.validators else {
                        continue;
                    };

                    let bls_keys = validators
                        .validators
                        .iter()
                        .map(|validator| validator.voting_key.clone())
                        .collect::<Vec<LazyPublicKey>>();
                    if let Err(err) = bls_cache.add_keys(bls_keys).await {
                        log::warn!("Failed caching bls keys {}", err);
                    }
```

2025-01-30 12:40 UTC, Eligioo commented on genesis/src/networks.rs
> +                .decompressed_keys
What would happen if you provide a genesis config without the `decompressed_keys` section? This object is added later on

2025-02-05 09:32 UTC, hrxi commented on bls/src/types/compressed_public_key.rs
> +        log::info!("decompressing {}", &self.to_hex()[..16]);
Done. I think it should be `INFO` or louder since it is a ~100 ms action and it's interesting to the person viewing the logs that an expensive action happened.

2025-02-05 09:32 UTC, hrxi commented on web-client/src/client/bls_cache.rs
> +                log::warn!("idb: Couldn't create database {}", err);
Done.

2025-02-05 09:32 UTC, hrxi commented on web-client/src/client/lib.rs
> +                    }
Done.

2025-02-05 09:35 UTC, hrxi commented on genesis/src/networks.rs
> +                .decompressed_keys
In this case, the keys in the genesis block would be decompressed at startup time. This `decompressed_keys` array would be empty and no decompressed keys would be extracted.

2025-02-05 17:37 UTC, nibhar approved these changes
LGTM

2025-02-06 15:13 UTC, hrxi commented
Rebased for merging.

2025-02-07 09:49 UTC, merged