Validator health status
nimiq/core-rs-albatross pull request #3207
Opened 2024-12-18 21:58 UTC by viquezclaudio

## What's in this pull request?

...
#### This fixes #___.

## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

2025-01-09 13:08 UTC, Eligioo commented on test-utils/src/validator.rs
> +            true,
Make `automatic_reactivate` a fn param for `build_validators` so it doesn't influence other tests?

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +    pub blk_cnt: u32,
```suggestion
    pub block_counter: u32,
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/micro.rs
> +            self.health_state.write().blk_cnt += 1;
```suggestion
            self.health_state.write().blk_cnt.saturating_add(1);
```
Prevent overflow

2025-01-09 13:08 UTC, Eligioo commented on validator/src/micro.rs
> +                break Some(Some(event));
```suggestion
                log::warn!(block = block.block_number(), "Not publishing block");
                break Some(Some(ProduceMicroBlockEvent::MicroBlock));
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +    /// For testing/debug purposes control wether produced blocks are published by the validator
```suggestion
    /// For testing/debug purposes control whether produced blocks are published by the validator
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +                    match validator_health {
```suggestion
                    match self.health_state.read().health {
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +    /// Number of blocks that we have produced in time(without being inactivated)
```suggestion
    /// Number of subsequent blocks that we have been produced without being inactivated
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +                            if self.health_state.read().blk_cnt >= VALIDATOR_HEALTH_THRESHOLD {
This logic doesn't seem to match with the original description: `If the validator is Yellow and is not deactivated in a quarter of an epoch, we change its status to Green.`

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +                            if self.health_state.read().blk_cnt >= VALIDATOR_HEALTH_THRESHOLD {
This logic doesn't seem to match with the original description: `If the validator is Red and is not deactivated in one epoch, we change its status to Yellow.`

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +                        match validator_health {
```suggestion
                        match self.health_state.read().health {
```

2025-01-09 13:08 UTC, Eligioo commented on validator/src/validator.rs
> +                                    "The validator needs human intervention, no automatic reactivate"
```suggestion
                                    "The validator needs human intervention, no automatic reactivation"
```

2025-01-31 10:40 UTC, Eligioo commented on validator/src/health.rs
> +    pub fn _set_publish_flag(&mut self, publish: bool) {
The method can be annotated with `#[cfg(test)]` such that it's only included in `cargo test` and not in `cargo build`.

2025-01-31 10:40 UTC, Eligioo commented on primitives/account/src/account/staking_contract/validator.rs
> +///      in the current epoch. The delay is function of the number of deactivations and is reduced
```suggestion
///      in the current epoch. The delay is a function of the number of deactivations and is reduced
```

2025-01-31 10:40 UTC, Eligioo commented on validator/src/health.rs
> +/// Struct that represents the overall health of a validator
`ValidatorHealthState` is an enum not a struct

2025-01-31 10:40 UTC, Eligioo commented on validator/src/health.rs
> +    /// Number of consecutive inactivations that have ocurred in the current epoch
```suggestion
    /// Number of consecutive inactivations that have occurred in the current epoch
```

2025-01-31 10:40 UTC, Eligioo commented on validator/src/health.rs
> +    /// Next block number where the re-activate transaction should be sent
```suggestion
    /// Next block number indicating when the re-activate transaction should be sent
```

2025-01-31 10:40 UTC, Eligioo commented on validator/src/validator.rs
> +                self.validator_health.write().reset_epoch();
Why would everything get reset once an epoch finalises? The 'health' of a validator doesn't suddenly improve if a new epoch starts.

2025-01-31 10:40 UTC, Eligioo commented on validator/src/micro.rs
> +            // Each successfull block will decrease the number of inactivations
```suggestion
            // Each successful block will decrease the number of inactivations
```

2025-01-31 10:40 UTC, Eligioo commented on validator/src/health.rs
> +            self.inactivations += 1;
saturating add?

2025-01-31 10:40 UTC, Eligioo commented on validator/tests/mock.rs
> +use nimiq_primitives::{coin::Coin, networks::NetworkId, policy::Policy};
Unused imports?

2025-01-31 10:40 UTC, Eligioo commented on validator/tests/mock.rs
> +use nimiq_transaction_builder::TransactionBuilder;
Same as above

2025-01-31 10:40 UTC, Eligioo commented on validator/tests/mock.rs
> +    events.take(30).for_each(|_| future::ready(())).await;
I guess you can take 50 here and get in the red state immediately. Testing if the validator got the yellow status is already covered in another test.

2025-03-11 16:05 UTC, nibhar requested changes
I think some changes made the distinction between red and yellow health go away. I would like to see some structural changes to the Validator Health struct and potentially removing the heap allocation as I think it is unnecessary.

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +    health: ValidatorHealthState,
As I understand it this is a derived value over the other fields of this struct. I would prefer then for this to not be stored explicitly, but instead be retrieved on a function call like `health(&self)` below.

It actually is only used in a single test, and there it is just enough check if it is `healthy() -> bool`. If there was a purpose to Yellow (or Red), it has been lost during one of the changes. 

I suggest to remove it entirely and use `healthy(&self) -> bool` instead. The enum can then also go.

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +    publish: bool,
I think this does not belong here. It should be done in the validator or in the network even.

If you insist on having it here, add `#[cfg(test)]` where appropriate to not include this in non testing builds.

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +            self.pending_reactivate = true;
Ok so this is a somewhat obscure way of referencing that some other piece of code is going to try and re-try for a reactivate and that in the meantime the node will remain inactive and thus not produce blocks.  

If my assessment here is correct then I think this should be asserted instead.
```
assert!(!self.pending_reactivate, "Cannot be inactivated when not active");
```
If not I prefer this be inverted:
```rust
if self.pending_reactivate {
  return;
}
...
```

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +            self.pending_reactivate = true;
What does `pending_reactivate` actually mean here? I do not see a reactivate being sent here, so it probably means something else.

I would rename this to `inactive`, or `currently_inactive`. If there is a reactivate currently pending is unknown, but also irrelevant for what this does.

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +        self.pending_reactivate = false;
What about the `reactivate_block_number`?

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +    pub fn reset_epoch(&mut self) {
Generally I would argue that maybe resetting on epoch is not the best, but if it does, should it not reset `reactivate_block_number` and `pending_reactivate` as well? Does an inactivation count of zero with `pending_reactivate = true` make any sense? As I see it you will then not only be inactive, but not even electable and thus should not have any slots at all..?

2025-03-11 16:05 UTC, nibhar commented on validator/src/micro.rs
> +            self.validator_health.write().block_produced();
I feel like this could be done in the validator instead and then we could get rid of the `Arc<RwLock<..>>`, as only the Validator hold the instance. 

The disabling of the publish would not be covered, but I would argue that is unrelated to the validator health anyways and should probably be implemented somewhere else.

2025-03-11 16:05 UTC, nibhar commented on validator/src/micro.rs
> +            }
I would want this to be moved into `Validator::publish_block`. There it can also be used for macro blocks at the same time.

2025-03-11 16:05 UTC, nibhar commented on validator/src/validator.rs
> +            validator_health: Arc::clone(&self.validator_health),
Why does the proxy need the validator health? If we remove this here and in the micro producer then the Arc and the RwLock can be removed. If this is only for testing then we might want to think about better alternatives for the testing purposes.

2025-03-11 16:05 UTC, nibhar commented on validator/src/health.rs
> +    reactivate_block_number: u32,
Is this related to Validator health? Might be a better fit where the reactivation actually happens.

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +    pub fn _set_publish_flag(&mut self, publish: bool) {
`#[cfg(test)]` is applied only in unittests and not integration tests, so I would leave it like this

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +    health: ValidatorHealthState,
I think the Green, Yellow, Red distinction is to convey that meaning to the validator operators in the logs (and I think it would be valuable to provide an RPC function as well to get the validator health) rather than just providing the number of consecutive deactivations a validator has experienced. 

But correct, this could be simplified to just keep track the number of consecutive deactivations and internally computing a delay based on this number without any notion of Good (green), Warning (yellow), Bad (red)

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +    publish: bool,
#[cfg(test)] is applied only in unittests and not integration tests so it cannot be used to filter out testing only fields.
another option would be to create a feature flag only for this purpose but i think thats unnecessary. 

I agree that this should be moved to the validator and not validator health. But then we wont be able to tweak this flag in runtime from the test, because we can only tweak from a test (or externally) whatever is exposed in the validator proxy 

Im open to suggestions

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +        self.pending_reactivate = false;
The reactivate block number would be computed the next time we are de-activated. 
So it is not necessary to compute it here, although i could compute it here just for completeness

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +    pub fn reset_epoch(&mut self) {
Same as above `reactivate_block_number`, is computed when we are deactivated so there is no need to compute it here.
We can decide if we want to reset every epoch or if we reset every X number of blocks, or we dont reset and we just stay with the current validator health. who makes this decision ?

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/micro.rs
> +            self.validator_health.write().block_produced();
How can we do this in the validator? because the validator only polls the micro producer but AFAIK it is not aware if the block was successfully produced and published

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/micro.rs
> +            }
I agree
But I would like to control the publish_flag externally from a test, so if I move it to the validator, how can I do that?

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/validator.rs
> +            validator_health: Arc::clone(&self.validator_health),
Yup, this is only for testing.
if theres a better alternative to control wether blocks are published or not, I would remove this Arc

2025-03-11 20:58 UTC, viquezclaudio commented on validator/src/health.rs
> +    reactivate_block_number: u32,
The reactivation happens within the validator. I put it here to update it when the `validator_health::inactivate` is called to keep everything together rather than having this number in the validator and updating it from the validator health.

2025-03-17 16:36 UTC, nibhar commented on validator/src/health.rs
> +    health: ValidatorHealthState,
Not storing `health` in the struct I would say we should do regardless. There is no benefit in doing so and calculating it on the fly is very cheap. If this will only be used for logging, and the logging is done internally, then i think the `fn healthy(&self) -> bool` is actually sufficient. Logging could then be done whenever a threshold is reached and the 'state' changes. 
While I would prefer that I think it would also be fine to keep the enum and have `fn health(&self) -> ValidatorHealthState`.

2025-03-17 16:44 UTC, nibhar commented on validator/src/micro.rs
> +            self.validator_health.write().block_produced();
I am not 100% sure about it, but in `Validator::poll_micro` the polling of the micro producer should give you the event, which should contain the micro block. You can check if it is a skip block or not, and that is going to be just as good as doing it here I would think. I would have to go look though.

2025-03-17 20:47 UTC, viquezclaudio commented on validator/src/micro.rs
> +            self.validator_health.write().block_produced();
Currently the block itself is not returned via the ProduceMicroBlock stream (which is the one that is being polled in `Validator::poll_micro` )

2025-03-18 10:48 UTC, nibhar commented on validator/src/micro.rs
> +            self.validator_health.write().block_produced();
Maybe you could add the skip blocks as distinct events from micro blocks.
```rust
enum ProduceMicroBlockEvent {
  MicroBlock,
  SkipBlock,
}
```
and use it then in `Validator::poll_micro`?

2025-03-18 10:56 UTC, nibhar commented on validator/src/health.rs
> +        self.pending_reactivate = false;
As it is not at all guaranteed that this number is not getting used in between a call to `reset_activations` and `inactivate` there is potential for inconsistent state. This should not make that assumption on the caller, it should present consistent state, no matter what the caller does.

2025-03-18 11:00 UTC, nibhar commented on validator/src/health.rs
> +    pub fn reset_epoch(&mut self) {
Same as above, the `reactivate_block_number` as well as `pending_reactivate` (now `inactive`) are accessible at all times. The presented state should be consistent. 

Do we need to reset this at all? It should be quasi self resetting in a way as soon as a validators actual health improves?

2026-09-01 20:36 UTC, closed without merging