Include unittest to create chain with txns
nimiq/core-rs-albatross pull request #583
Opened 2022-01-28 20:23 UTC by viquezclaudio

Created a new unittest that can be used to exercise a chain
with transactions indefinitely

2022-01-28 23:09 UTC, jsdanielh requested changes

2022-01-28 23:09 UTC, jsdanielh commented on block-production/Cargo.toml
> +rand = "0.8"
Maybe a `dev` dependency instad?

2022-01-28 23:09 UTC, jsdanielh commented on block-production/tests/mod.rs
> +use tempdir::TempDir;
We normally separate internal vs external dependencies... I would put them above as they were

2022-01-28 23:09 UTC, jsdanielh commented on test-utils/src/blockchain.rs
> +use nimiq_primitives::coin::Coin;
I would place them below with nimiq dependencies

2022-01-28 23:09 UTC, jsdanielh commented on block-production/tests/mod.rs
> +const VOLATILE_ENV: bool = false;
I would consider leaving the default in `true` since most of our tests run in a volatile environment

2022-01-28 23:29 UTC, viquezclaudio commented
changes applied @jsdanielh

2022-01-29 00:08 UTC, jsdanielh approved these changes

2022-02-01 17:43 UTC, merged